CREATE TABLE IF NOT EXISTS public.dog_sightings (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description text,
    location public.geometry(Point,4326) NOT NULL,
    address text,
    landmark text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.dog_photos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sighting_id integer NOT NULL REFERENCES public.dog_sightings(id) ON DELETE CASCADE,
    photo_path text NOT NULL,
    created_at timestamp without time zone DEFAULT now()
);

CREATE INDEX IF NOT EXISTS dog_sightings_location_gist_idx
    ON public.dog_sightings
    USING GIST (location);

CREATE INDEX IF NOT EXISTS dog_sightings_created_at_idx
    ON public.dog_sightings (created_at DESC);
